### ISSUE TITLE
pycharm is not started?

### ISSUE THREAD

**Issue by sxzqcsq** [mactavishmeng/mitmserver#1]
when i run the script in my pycharm, i found this program can not run as usual, can you help me to sovle this problem, thanks

**Comment by mactavishmeng** [comment]
> when i run the script in my pycharm, i found this program can not run as usual, can you help me to sovle this problem, thanks

Hello sxzqcsq, can you share more details about your problem?

**Comment by sxzqcsq** [comment]
E:\mitmserver\venv\Scripts\python.exe E:/mitmserver/mitmserver.py
simple DNS server is running
Unhandled exception in thread started by <function startdns at 0x000002E959AF0A68>
Traceback (most recent call last):
  File "E:/mitmserver/mitmserver.py", line 39, in startdns
    sev.start()  # start DNS server
  File "E:\mitmserver\dnsserver.py", line 118, in start
    server = socketserver.UDPServer((HOST, PORT), SinDNSUDPHandler)
  File "C:\Users\Junlin\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\Junlin\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10048] 
simple http server, address:0.0.0.0:80
simple https server, address:0.0.0.0:443

this is the error on console, can you help me to sovle it, thanks

**Comment by mactavishmeng** [comment]
> E:\mitmserver\venv\Scripts\python.exe E:/mitmserver/mitmserver.py
> simple DNS server is running
> Unhandled exception in thread started by <function startdns at 0x000002E959AF0A68>
> Traceback (most recent call last):
> File "E:/mitmserver/mitmserver.py", line 39, in startdns
> sev.start() # start DNS server
> File "E:\mitmserver\dnsserver.py", line 118, in start
> server = socketserver.UDPServer((HOST, PORT), SinDNSUDPHandler)
> File "C:\Users\Junlin\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 452, in **init**
> self.server_bind()
> File "C:\Users\Junlin\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 466, in server_bind
> self.socket.bind(self.server_address)
> OSError: [WinError 10048]
> simple http server, address:0.0.0.0:80
> simple https server, address:0.0.0.0:443
> 
> this is the error on console, can you help me to sovle it, thanks

it seems that your port 53 is used by another program or service. Try to use `netstat` , find out PID of the program and kill it. BTW, if you're using Windows 7 or Windows 10, make sure that the ICS service is not running. Good luck : )

**Comment by sxzqcsq** [comment]
i use this command to find the PID of port 53, that is the ICS service. When i close this service, i can run   
the script very well, thans guy
